<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXJxyGSu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXJxyGSu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXJxyGSu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXJxyGSu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXJxyGSu\App_KernelDevDebugContainer([
    'container.build_hash' => 'XJxyGSu',
    'container.build_id' => '4c2c9dc0',
    'container.build_time' => 1652789903,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXJxyGSu');
